{% set name = "sqlite-zstd" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/phiresky/sqlite-zstd/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c29d5229dc2d6b7fad677c3115155918d0cb34897554675213f10cac8f1cb266

build:
  number: 0
  skip: true  # [not linux] # macos will need >=10.12
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo build --release --features build_extension
    - mkdir -p $PREFIX/lib
    - find . -name *libsqlite_zstd.so*
    - cp $(find . -name libsqlite_zstd.so | tail -n 1) $PREFIX/lib

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  run:
    - sqlite

test:
  commands:
    - echo '.quit' | sqlite3 -cmd '.load libsqlite_zstd.so'

about:
  home: https://github.com/phiresky/sqlite-zstd
  summary: 'Transparent dictionary-based row-level compression for SQLite'
  description: |
    Extension for sqlite that provides transparent dictionary-based row-level
    compression for sqlite. This basically allows you to compress entries in a
    sqlite database almost as well as if you were compressing the whole DB
    file, but while retaining random access.
  license: LGPL-3.0-only
  license_family: LGPL
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - matthiasdiener
