{% set name = "sqlite-zstd" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/phiresky/sqlite-zstd/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 86fb7e77b2f5d2d5db43d17a35f9c1d0e1587719dd450bc1fb39e8d58ea48f65

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python

outputs:
  - name: sqlite-zstd
    script: build_lib.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('rust') }}
        - {{ stdlib('c') }}
        - cargo-bundle-licenses
      run:
        - sqlite

    test:
      commands:
        - echo '.quit' | sqlite3 -cmd ".load libsqlite_zstd${SHLIB_EXT}" 2>&1 | grep sqlite_zstd::create_extension

  - name: sqlite-zstd-python
    script: build_py.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('rust') }}
        - {{ stdlib('c') }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools >=61.2
        - setuptools-scm >=6.2
        - setuptools-rust
        - sqlite
      run:
        - python
        - sqlite

    test:
      imports:
        - sqlite_zstd
      commands:
        - pip check
      requires:
        - pip



about:
  home: https://github.com/phiresky/sqlite-zstd
  summary: 'Transparent dictionary-based row-level compression for SQLite'
  description: |
    Extension for sqlite that provides transparent dictionary-based row-level
    compression for sqlite. This basically allows you to compress entries in a
    sqlite database almost as well as if you were compressing the whole DB
    file, but while retaining random access.
  license: LGPL-3.0-only
  license_family: LGPL
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - matthiasdiener
